import type { StarterSeedDefinition, StarterSeedInstrumentRole } from './types';

function instrumentRoles(entries: Array<[string, string, string]>): StarterSeedInstrumentRole[] {
  return entries.map(([engineId, jurisdiction, role]) => ({ engineId, jurisdiction, role }));
}

export const STARTER_SEEDS: StarterSeedDefinition[] = [
  // ---------------------------------------------------------------------------
  // POSITIVE AFFECT — different species of FUCK YES, never generic "happy"
  // ---------------------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'affect-divine-exultation',
    name: 'DIVINE EXULTATION',
    category: 'affect',
    description: 'Luminous upward release: choir-sized joy, widening harmony, and arrival that feels bigger every time.',
    defaultIntensity: 88,
    tags: ['joy', 'choir', 'uplift', 'triumph'],
    owns: ['emotionalValence', 'harmonicTrajectory', 'vocalBehavior'],
    biases: ['ascending register', 'open consonance', 'voice recruitment', 'large final arrival'],
    protects: ['the emotional reward signal stays unmistakably positive'],
    forbids: ['melancholy creep', 'wistful bridge', 'bittersweet resolution', 'solemn funeral pacing'],
    operators: [
      'Each major return opens the harmony upward and recruits additional voices.',
      'Suspended tension may delay release, but every major release resolves toward brightness rather than grief.',
      'Let the final third feel physically larger through register, participation, and harmonic openness rather than simple loudness.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'narrator-and-mob', strength: 52 }],
      musicMechanismRefs: [
        { id: 'communal-infection', strength: 88 },
        { id: 'group-unison-burst', strength: 82 },
        { id: 'anchor-survival', strength: 64 },
      ],
      musicControlDeltas: { socialInfection: 28, castSize: 22, anchorStrength: 10, kineticDensity: 8 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-communal-joy-riot',
    name: 'COMMUNAL JOY RIOT',
    category: 'affect',
    description: 'Happiness spreads person to person until the room becomes part of the arrangement.',
    defaultIntensity: 86,
    tags: ['joy', 'crowd', 'claps', 'contagious'],
    owns: ['emotionalValence', 'socialBehavior', 'vocalBehavior'],
    biases: ['claps', 'stomps', 'answering voices', 'dance-circle escalation'],
    protects: ['participation keeps increasing because people are delighted, not threatened'],
    forbids: ['angry mob energy', 'dirge pacing', 'detached coolness'],
    operators: [
      'Begin with a small social population and recruit performers only after audible triggers.',
      'Every newly recruited voice should bring a new physical action: clap, stomp, answer, chant, or brief unison.',
      'Escalation should feel contagious and bodily legible rather than like a wall of choir.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'coupled-stampede', strength: 82 }],
      musicMechanismRefs: [
        { id: 'communal-infection', strength: 96 },
        { id: 'body-percussion', strength: 86 },
        { id: 'call-response', strength: 84 },
      ],
      musicControlDeltas: { socialInfection: 38, coupling: 14, kineticDensity: 18, castSize: 28 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-victory-lap',
    name: 'VICTORY LAP',
    category: 'affect',
    description: 'Swaggering triumph: forward motion, sharp arrivals, ridiculous confidence, zero brooding.',
    defaultIntensity: 82,
    tags: ['triumph', 'swagger', 'forward', 'celebration'],
    owns: ['emotionalValence', 'performance', 'harmonicTrajectory'],
    biases: ['hard downbeats', 'brass-like punctuation', 'confident bass motion', 'clean arrivals'],
    protects: ['the performance sounds like it has already won'],
    forbids: ['self-doubt', 'yearning', 'defeat-coded minor collapse'],
    operators: [
      'Make each return more certain and rhythmically decisive than the previous one.',
      'Use short high-impact ensemble punctuation after successful arrivals.',
      'Let confidence come from timing and commitment, not from flattening the music into four-square bombast.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'group-unison-burst', strength: 82 },
        { id: 'anchor-survival', strength: 70 },
        { id: 'hard-interrupts', strength: 42 },
      ],
      musicControlDeltas: { kineticDensity: 16, interruption: 8, anchorStrength: 18 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-childlike-delight',
    name: 'CHILDLIKE DELIGHT',
    category: 'affect',
    description: 'Bright curiosity and surprise without becoming nursery music.',
    defaultIntensity: 76,
    tags: ['delight', 'play', 'sparkle', 'curiosity'],
    owns: ['emotionalValence', 'melodicBehavior'],
    biases: ['bouncing intervals', 'tiny surprises', 'bells and plucks', 'quick recoveries'],
    protects: ['curiosity remains energetic and non-cynical'],
    forbids: ['lullaby pacing', 'sentimental nostalgia', 'sad-pretty prettiness'],
    operators: [
      'Reward small unexpected melodic discoveries with immediate answering gestures.',
      'Use short upward rebounds after local surprises so motion never slumps.',
      'Let ornaments act like discovered toys: introduced clearly, used once or twice, then replaced before they become wallpaper.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'false-resolution', strength: 68 },
        { id: 'vocal-relay', strength: 44 },
      ],
      musicControlDeltas: { kineticDensity: 20, interruption: 12, coupling: 6 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-feral-euphoria',
    name: 'FERAL EUPHORIA',
    category: 'affect',
    description: 'Joy has escaped containment and is now sprinting through the building.',
    defaultIntensity: 92,
    tags: ['euphoria', 'fast', 'wild', 'positive'],
    owns: ['emotionalValence', 'kineticDensity', 'vocalBehavior'],
    biases: ['rapid entries', 'overexcited fills', 'shouted interjections', 'rising participation'],
    protects: ['the frenzy remains exhilarated rather than panicked or hostile'],
    forbids: ['fear coding', 'ominous harmony', 'exhausted comedown'],
    operators: [
      'Shorten the time between distinct positive events as the track develops.',
      'Let performers audibly trip over each other because they are eager to participate.',
      'Rotate fast events between actors so high density remains legible.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'panic-engine', strength: 72 }],
      musicMechanismRefs: [
        { id: 'double-time-activity', strength: 88 },
        { id: 'communal-infection', strength: 86 },
        { id: 'hard-interrupts', strength: 68 },
      ],
      musicControlDeltas: { kineticDensity: 38, socialInfection: 28, interruption: 18, castSize: 16 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-laughing-fit',
    name: 'LAUGHING FIT',
    category: 'affect',
    description: 'Laughter is a causal musical system: one crack-up changes what everybody else does.',
    defaultIntensity: 78,
    tags: ['laughter', 'contagion', 'breath', 'joy'],
    owns: ['emotionalValence', 'socialBehavior', 'vocalBehavior', 'eventLogic'],
    biases: ['giggle pickups', 'breath rhythm', 'infectious responses', 'broken composure'],
    protects: ['laughter remains recognizably human and contagious'],
    forbids: ['creepy laughter bed', 'villain laughter', 'random canned laughter'],
    operators: [
      'Begin with one audible laugh event and make it trigger a concrete response elsewhere in the arrangement.',
      'Allow laughter to migrate from interruption to rhythm to group response without becoming constant wallpaper.',
      'Use breath recovery after laughter as a rhythmic reset or pickup into the next event.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'event-driven-form', strength: 78 },
        { id: 'communal-infection', strength: 88 },
        { id: 'vocal-relay', strength: 70 },
      ],
      musicControlDeltas: { socialInfection: 30, interruption: 20, castSize: 18 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-sunburst',
    name: 'SUNBURST',
    category: 'affect',
    description: 'Brightness itself expands: register, stereo space, and harmonic openness bloom outward.',
    defaultIntensity: 80,
    tags: ['bright', 'uplift', 'expansion', 'arrival'],
    owns: ['emotionalValence', 'harmonicTrajectory', 'spatialPerception'],
    biases: ['widening register', 'expanding stereo image', 'open intervals', 'ascending trajectories'],
    protects: ['brightness increases without becoming sentimental'],
    forbids: ['dreamy slowdown', 'wistfulness', 'ambient drift'],
    operators: [
      'Widen pitch register and apparent spatial width at major structural returns.',
      'Preserve a graspable pulse while upper material becomes progressively more radiant and active.',
      'Use brightness as an expanding physical field rather than a static timbre adjective.',
    ],
    outputs: {
      musicMechanismRefs: [{ id: 'anchor-survival', strength: 72 }],
      musicControlDeltas: { anchorStrength: 18, kineticDensity: 10, stemminess: 8 },
    },
  },
  {
    schemaVersion: 1,
    id: 'affect-mischievous-delight',
    name: 'MISCHIEVOUS DELIGHT',
    category: 'affect',
    description: 'Shit-eating-grin music: teasing, nimble, rhythmically playful, but never mean.',
    defaultIntensity: 76,
    tags: ['mischief', 'joy', 'funky', 'teasing'],
    owns: ['emotionalValence', 'rhythmicBehavior', 'performance'],
    biases: ['fake stops', 'syncopated feints', 'wrong-note recoveries', 'quick callbacks'],
    protects: ['the joke remains musically rewarding even if the listener misses the joke'],
    forbids: ['smug detachment', 'mean-spiritedness', 'sluggish comedy'],
    operators: [
      'Set up short expectations and violate them rhythmically without losing the common pulse.',
      'Turn one apparent mistake into a recurring hook or cue.',
      'Use fake endings or pauses only when they create a concrete re-entry payoff.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'false-resolution', strength: 84 },
        { id: 'hard-interrupts', strength: 72 },
        { id: 'event-driven-form', strength: 56 },
      ],
      musicControlDeltas: { interruption: 24, coupling: 8, kineticDensity: 14 },
    },
  },

  // ---------------------------------------------------------------------------
  // PSYCHEDELIC / ALTERED PERCEPTION — operational phenomenology, not genre
  // ---------------------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'psy-lsd-prismatic-recursion',
    name: 'LSD — PRISMATIC RECURSION',
    category: 'psychedelic',
    description: 'Motifs refract into spectral relatives, phase against themselves, and recombine slightly wrong.',
    defaultIntensity: 84,
    tags: ['lsd', 'recursion', 'refraction', 'phase'],
    owns: ['temporalPerception', 'melodicBehavior', 'timbre'],
    biases: ['motif copies', 'phase offset', 'spectral brightness', 'micro-variation'],
    protects: ['the original motif remains traceable through its descendants'],
    forbids: ['generic psychedelic wash', 'featureless reverb soup'],
    operators: [
      'Clone a short motif into several near-relatives that differ by contour detail, register, or entry offset.',
      'Let copies phase apart, then force them to recombine at recognizable alignment points.',
      'Each recurrence must preserve ancestry while exposing one new mutation.',
    ],
    outputs: {
      realityEngineIds: ['altered-lsd-sensory-crosswire'],
      musicRecipeRefs: [{ id: 'anchor-under-siege', strength: 74 }],
      musicMechanismRefs: [
        { id: 'role-migration', strength: 72 },
        { id: 'false-resolution', strength: 74 },
      ],
      musicControlDeltas: { coupling: 18, anchorStrength: 22, kineticDensity: 12 },
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-lsd-time-breathing',
    name: 'LSD — TIME IS BREATHING',
    category: 'psychedelic',
    description: 'Phrase lengths inhale and exhale while the underlying pulse remains something the body can still grab.',
    defaultIntensity: 82,
    tags: ['lsd', 'time', 'elastic', 'pulse'],
    owns: ['temporalPerception', 'rhythmicBehavior'],
    biases: ['elastic subdivision', 'phrase dilation', 'stable substrate', 'delayed returns'],
    protects: ['at least one stable temporal reference remains audible'],
    forbids: ['random tempo wobble', 'rubato mush'],
    operators: [
      'Hold one base pulse stable while subdivision density expands and contracts in long breathing arcs.',
      'Stretch one event class while compressing another so two temporal scales coexist.',
      'Return to exact alignment periodically so the distortion remains measurable.',
    ],
    outputs: {
      realityEngineIds: ['altered-lsd-sensory-crosswire'],
      musicRecipeRefs: [{ id: 'double-time-hallucination', strength: 76 }],
      musicMechanismRefs: [{ id: 'meter-collision', strength: 62 }],
      musicControlDeltas: { coupling: 22, kineticDensity: 18, anchorStrength: 12 },
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-lsd-hyper-salience',
    name: 'LSD — EVERYTHING IS HILARIOUSLY IMPORTANT',
    category: 'psychedelic',
    description: 'Tiny background events acquire absurd structural authority and the whole arrangement reacts to them.',
    defaultIntensity: 86,
    tags: ['lsd', 'salience', 'event', 'attention'],
    owns: ['eventLogic', 'form', 'temporalPerception'],
    biases: ['tiny cues', 'background promotion', 'causal overreaction'],
    protects: ['each promoted detail remains identifiable as the event that caused the change'],
    forbids: ['random jump cuts with no cause', 'decorative weirdness'],
    operators: [
      'Choose small audible events and let each one trigger a disproportionate but traceable arrangement change.',
      'Promote former background material into temporary structural authority.',
      'After a promoted cue acts, preserve at least one downstream consequence instead of resetting immediately.',
    ],
    outputs: {
      realityEngineIds: ['altered-lsd-sensory-crosswire'],
      musicRecipeRefs: [{ id: 'event-driven-variety-show', strength: 88 }],
      musicMechanismRefs: [{ id: 'hard-interrupts', strength: 64 }],
      musicControlDeltas: { interruption: 26, kineticDensity: 16 },
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-lsd-kaleidoscope-machine',
    name: 'LSD — KALEIDOSCOPE MACHINE',
    category: 'psychedelic',
    description: 'The same limited ingredients keep rotating into different adjacencies instead of simply accumulating.',
    defaultIntensity: 82,
    tags: ['lsd', 'permutation', 'rotation', 'cells'],
    owns: ['form', 'arrangement', 'rhythmicBehavior'],
    biases: ['cell permutation', 'rotating roles', 'limited palette', 'recognizable pieces'],
    protects: ['the ingredient set stays small enough to recognize'],
    forbids: ['endless additive layering', 'new element every bar'],
    operators: [
      'Choose a small set of rhythmic and melodic cells and change their adjacency, ownership, and entry order.',
      'Do not add a new cell merely to create novelty; reconfigure the existing set first.',
      'Let one cell periodically become the anchor while the others rotate around it.',
    ],
    outputs: {
      realityEngineIds: ['altered-lsd-sensory-crosswire'],
      musicMechanismRefs: [
        { id: 'role-migration', strength: 84 },
        { id: 'vocal-relay', strength: 58 },
        { id: 'anchor-survival', strength: 70 },
      ],
      musicControlDeltas: { coupling: 16, anchorStrength: 18, stemminess: 10 },
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-dmt-hyperspatial-arrival',
    name: 'DMT — HYPERSPATIAL ARRIVAL',
    category: 'psychedelic',
    description: 'Immediate impossible density: no gentle fade-in, but clear anchors keep flashing through the overload.',
    defaultIntensity: 92,
    tags: ['dmt', 'arrival', 'density', 'hyperspatial'],
    owns: ['temporalPerception', 'kineticDensity', 'spatialPerception'],
    biases: ['instant density', 'nested scales', 'sharp clarity', 'rapid reclassification'],
    protects: ['brief intelligible anchors keep puncturing the overload'],
    forbids: ['slow ambient onset', 'muddy wall of sound'],
    operators: [
      'Begin near the target complexity instead of spending a long intro approaching it.',
      'Rotate dense events among distinct actors and registers so overload remains dissectable.',
      'Insert extremely clear anchor flashes that momentarily reveal the governing structure.',
    ],
    outputs: {
      realityEngineIds: ['altered-dmt-entity-reception'],
      musicRecipeRefs: [
        { id: 'panic-engine', strength: 82 },
        { id: 'anchor-under-siege', strength: 74 },
      ],
      musicControlDeltas: { kineticDensity: 38, stemminess: 18, anchorStrength: 18, interruption: 18 },
      realityChaos: 4,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-dmt-alien-language-engine',
    name: 'DMT — ALIEN LANGUAGE ENGINE',
    category: 'psychedelic',
    description: 'Voices and instruments exchange linguistic jobs until phonetics becomes orchestration.',
    defaultIntensity: 88,
    tags: ['dmt', 'language', 'voice', 'phonetic'],
    owns: ['vocalBehavior', 'timbre', 'melodicBehavior'],
    biases: ['phonetic percussion', 'voice/instrument exchange', 'nonhuman call-response'],
    protects: ['phonetic events perform actual musical work'],
    forbids: ['random gibberish pasted over ordinary accompaniment'],
    operators: [
      'Convert consonant attacks into percussion, sustained vowels into pitch carriers, and nasals into resonance.',
      'Let an instrument inherit a vocal function, then let a voice steal back one instrumental function.',
      'Make each phonetic class causally tied to a musical role rather than decorative nonsense.',
    ],
    outputs: {
      realityEngineIds: ['altered-dmt-entity-reception'],
      musicRecipeRefs: [{ id: 'vocal-relay-riot', strength: 92 }],
      musicMechanismRefs: [
        { id: 'phonetic-percussion', strength: 96 },
        { id: 'role-migration', strength: 82 },
      ],
      musicControlDeltas: { castSize: 20, stemminess: 20, kineticDensity: 24 },
      realityChaos: 4,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-dmt-impossible-intelligence',
    name: 'DMT — IMPOSSIBLE INTELLIGENCE',
    category: 'psychedelic',
    description: 'The music demonstrates a rule, masters it, then reveals that rule was only a component of a larger one.',
    defaultIntensity: 90,
    tags: ['dmt', 'rule', 'nested', 'intelligence'],
    owns: ['form', 'eventLogic', 'rhythmicBehavior'],
    biases: ['nested rule discovery', 'clean demonstrations', 'later reinterpretation'],
    protects: ['every revealed higher-order rule explains something previously heard'],
    forbids: ['arbitrary complexity', 'random rule changes'],
    operators: [
      'Establish one strange but learnable rule and obey it precisely long enough for the listener to detect it.',
      'Reveal a second rule that explains why the first behaved as it did.',
      'Keep earlier evidence valid under the new rule rather than discarding it.',
    ],
    outputs: {
      realityEngineIds: ['altered-dmt-entity-reception'],
      musicRecipeRefs: [{ id: 'jurisdiction-crash-test', strength: 86 }],
      musicMechanismRefs: [
        { id: 'event-driven-form', strength: 82 },
        { id: 'anchor-survival', strength: 66 },
      ],
      musicControlDeltas: { coupling: 22, anchorStrength: 16, interruption: 14 },
      realityChaos: 4,
    },
  },
  {
    schemaVersion: 1,
    id: 'psy-salvia-wrong-gravity',
    name: 'SALVIA — WRONG GRAVITY',
    category: 'psychedelic',
    description: 'Musical functions fall sideways: melody behaves like percussion, bass migrates upward, accents become harmony.',
    defaultIntensity: 88,
    tags: ['salvia', 'role-exchange', 'wrongness', 'gravity'],
    owns: ['arrangement', 'rhythmicBehavior', 'timbre'],
    biases: ['role exchange', 'functional inversion', 'stable anchor'],
    protects: ['the exchanged function remains recognizable even in the wrong owner'],
    forbids: ['simple instrument swaps with unchanged behavior'],
    operators: [
      'Move one musical function into a source that normally should not own it while preserving the function itself.',
      'Let the previous owner continue doing something else instead of disappearing.',
      'Repeat the transfer with a different function only after the first wrong ownership is legible.',
    ],
    outputs: {
      realityEngineIds: ['altered-salvia-object-eternity'],
      musicMechanismRefs: [
        { id: 'role-migration', strength: 96 },
        { id: 'anchor-survival', strength: 76 },
      ],
      musicControlDeltas: { stemminess: 18, coupling: 12, anchorStrength: 20 },
      realityChaos: 4,
    },
  },

  // ---------------------------------------------------------------------------
  // MOTION / KINETIC STATES
  // ---------------------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'motion-cant-sit-still',
    name: 'CAN\'T SIT STILL',
    category: 'motion',
    description: 'Every phrase contains forward bodily motion; no section is allowed to sag.',
    defaultIntensity: 84,
    tags: ['motion', 'upbeat', 'drive'],
    owns: ['kineticDensity', 'rhythmicBehavior'],
    biases: ['active subdivision', 'forward bass', 'short rests', 'quick pickups'],
    protects: ['forward momentum remains audible even during sparse sections'],
    forbids: ['dragging half-time breakdown', 'static ambient interlude'],
    operators: [
      'Whenever one layer holds a long value, another layer must carry forward motion.',
      'Use pickups and short anticipations to pull phrases into their next event.',
    ],
    outputs: {
      musicMechanismRefs: [{ id: 'double-time-activity', strength: 78 }],
      musicControlDeltas: { kineticDensity: 30 },
    },
  },
  {
    schemaVersion: 1,
    id: 'motion-double-time-bloodstream',
    name: 'DOUBLE-TIME BLOODSTREAM',
    category: 'motion',
    description: 'The skeleton can walk while the bloodstream sprints.',
    defaultIntensity: 90,
    tags: ['motion', 'double-time', 'activity-rate'],
    owns: ['kineticDensity', 'rhythmicBehavior'],
    biases: ['moderate base pulse', 'high event rate', 'fast ornaments'],
    protects: ['the base pulse remains bodily graspable'],
    forbids: ['solving energy only by raising BPM'],
    operators: [
      'Keep the base tempo moderate while secondary activity runs at roughly double the event rate.',
      'Rotate fast activity between percussion, syllables, and ornament rather than stacking it all continuously.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'double-time-hallucination', strength: 96 }],
      musicControlDeltas: { kineticDensity: 36, stemminess: 10 },
    },
  },
  {
    schemaVersion: 1,
    id: 'motion-pinball',
    name: 'PINBALL',
    category: 'motion',
    description: 'Energy ricochets between registers and performers instead of traveling in one line.',
    defaultIntensity: 80,
    tags: ['motion', 'ricochet', 'handoff'],
    owns: ['kineticDensity', 'spatialPerception', 'arrangement'],
    biases: ['rapid handoffs', 'register jumps', 'short answering hits'],
    protects: ['each ricochet has a clear source and destination'],
    forbids: ['continuous everybody-playing density'],
    operators: [
      'Pass short high-energy events between separated registers or actors.',
      'Do not repeat the same source twice when another available actor can catch the event.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'vocal-relay', strength: 66 },
        { id: 'role-migration', strength: 80 },
      ],
      musicControlDeltas: { kineticDensity: 24, stemminess: 18, castSize: 10 },
    },
  },
  {
    schemaVersion: 1,
    id: 'motion-spring-loaded',
    name: 'SPRING-LOADED',
    category: 'motion',
    description: 'Downward pressure immediately rebounds upward; rhythm behaves like a compressed spring.',
    defaultIntensity: 78,
    tags: ['motion', 'bounce', 'rebound'],
    owns: ['rhythmicBehavior', 'melodicBehavior'],
    biases: ['offbeat rebound', 'short compression', 'upward recovery'],
    protects: ['every heavy event produces a rebound rather than a slump'],
    forbids: ['slow collapse', 'dead-weight groove'],
    operators: [
      'Pair heavy or low events with fast upward rhythmic or melodic rebounds.',
      'Use compression-release cycles at multiple phrase scales without changing the underlying emotional positivity.',
    ],
    outputs: {
      musicMechanismRefs: [{ id: 'false-resolution', strength: 68 }],
      musicControlDeltas: { kineticDensity: 18, coupling: 10 },
    },
  },
  {
    schemaVersion: 1,
    id: 'motion-rocket-takeoff',
    name: 'ROCKET TAKEOFF',
    category: 'motion',
    description: 'Continuous perceived acceleration without requiring continuous BPM acceleration.',
    defaultIntensity: 82,
    tags: ['motion', 'acceleration', 'build'],
    owns: ['kineticDensity', 'form'],
    biases: ['shorter event spacing', 'higher register', 'denser participation'],
    protects: ['perceived acceleration is created by changing several dimensions, not just tempo'],
    forbids: ['single endless crescendo', 'tempo-only acceleration'],
    operators: [
      'Increase event arrival rate, register height, and social participation in staggered stages.',
      'Hold at least one parameter fixed during each stage so acceleration remains perceivable rather than blurry.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'panic-engine', strength: 64 }],
      musicControlDeltas: { kineticDensity: 28, socialInfection: 12, interruption: 10 },
    },
  },
  {
    schemaVersion: 1,
    id: 'motion-stampede',
    name: 'COUPLED STAMPEDE MOTION',
    category: 'motion',
    description: 'Several bodily groupings share one substrate and push forward together.',
    defaultIntensity: 88,
    tags: ['motion', 'coupling', 'stomp', 'group'],
    owns: ['rhythmicBehavior', 'kineticDensity'],
    biases: ['3:2 grouping', 'body percussion', 'shared alignment'],
    protects: ['multiple rhythmic truths remain danceably connected'],
    forbids: ['random polymeter', 'ungraspable metric soup'],
    operators: [
      'Keep a common pulse substrate while separate populations accent incompatible groupings.',
      'Use recurring alignment points as moments of collective physical impact.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'coupled-stampede', strength: 96 }],
      musicControlDeltas: { coupling: 36, kineticDensity: 24, socialInfection: 18 },
    },
  },

  // ---------------------------------------------------------------------------
  // SOCIAL STATES
  // ---------------------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'social-one-person-starts-party',
    name: 'ONE PERSON STARTS A PARTY',
    category: 'social',
    description: 'Solo voice recruits an answer, then a group, then a room.',
    defaultIntensity: 84,
    tags: ['social', 'recruitment', 'party'],
    owns: ['socialBehavior', 'vocalBehavior'],
    biases: ['solo opening', 'answering voice', 'small group', 'crowd'],
    protects: ['the order of recruitment stays audible'],
    forbids: ['full choir from bar one'],
    operators: [
      'Stage recruitment in a visible sequence: solo → answer → small group → crowd.',
      'Each population inherits one audible behavior from the population that recruited it.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'communal-infection', strength: 96 },
        { id: 'vocal-cast', strength: 76 },
      ],
      musicControlDeltas: { socialInfection: 38, castSize: 30 },
    },
  },
  {
    schemaVersion: 1,
    id: 'social-call-response-epidemic',
    name: 'CALL + RESPONSE EPIDEMIC',
    category: 'social',
    description: 'Answers multiply until response itself becomes the form.',
    defaultIntensity: 82,
    tags: ['social', 'call-response', 'infection'],
    owns: ['socialBehavior', 'eventLogic'],
    biases: ['answers', 'echoing populations', 'escalating response'],
    protects: ['calls remain distinguishable from responses'],
    forbids: ['generic backing-vocal wash'],
    operators: [
      'Every successful response may become the next call for a different population.',
      'Increase the number of responding groups without erasing the original call/answer distinction.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'call-response', strength: 96 },
        { id: 'communal-infection', strength: 82 },
      ],
      musicControlDeltas: { socialInfection: 32, castSize: 22 },
    },
  },
  {
    schemaVersion: 1,
    id: 'social-choir-possession',
    name: 'CHOIR POSSESSION',
    category: 'social',
    description: 'A choir gradually takes over jobs that originally belonged to the band or narrator.',
    defaultIntensity: 80,
    tags: ['social', 'choir', 'role-exchange'],
    owns: ['socialBehavior', 'vocalBehavior', 'arrangement'],
    biases: ['voice takeover', 'group rhythm', 'harmonic mass'],
    protects: ['the choir remains a population with jobs, not a pad'],
    forbids: ['continuous wordless choir wallpaper'],
    operators: [
      'Start the choir in one narrow role, then let it inherit rhythm, punctuation, or anchor functions one at a time.',
      'Whenever the choir takes a job, the previous owner must adapt instead of simply doubling it.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'role-migration', strength: 82 },
        { id: 'vocal-cast', strength: 78 },
        { id: 'group-unison-burst', strength: 72 },
      ],
      musicControlDeltas: { castSize: 30, socialInfection: 24, stemminess: 12 },
    },
  },
  {
    schemaVersion: 1,
    id: 'social-narrator-loses-room',
    name: 'NARRATOR LOSING CONTROL OF THE ROOM',
    category: 'social',
    description: 'One intelligible authority keeps trying to continue while increasingly excited humans interfere.',
    defaultIntensity: 88,
    tags: ['social', 'narrator', 'mob', 'interruptions'],
    owns: ['socialBehavior', 'vocalBehavior', 'eventLogic'],
    biases: ['dry narrator', 'crowd interruptions', 'attempted resets'],
    protects: ['the narrator remains understandable enough to anchor the chaos'],
    forbids: ['narrator disappears permanently too early'],
    operators: [
      'After each crowd intrusion, force the narrator to attempt one clean procedural reset.',
      'Let repeated reset attempts become shorter as the room becomes more participatory.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'narrator-and-mob', strength: 96 }],
      musicControlDeltas: { socialInfection: 34, interruption: 28, castSize: 26, anchorStrength: 16 },
    },
  },
  {
    schemaVersion: 1,
    id: 'social-everybody-has-job',
    name: 'EVERYBODY HAS A JOB',
    category: 'social',
    description: 'Host, lead, crowd, small group, freak voice, and band each own different responsibilities.',
    defaultIntensity: 84,
    tags: ['social', 'cast', 'roles'],
    owns: ['cast', 'vocalBehavior', 'arrangement'],
    biases: ['distinct populations', 'entrance conditions', 'role separation'],
    protects: ['each population remains distinguishable by job'],
    forbids: ['lead plus anonymous backing singers'],
    operators: [
      'Assign each population one primary information or musical function before it enters.',
      'Allow later role borrowing only when the original owner remains identifiable.',
    ],
    outputs: {
      musicRecipeRefs: [{ id: 'cast-of-freaks', strength: 96 }],
      musicControlDeltas: { castSize: 38, stemminess: 24, socialInfection: 18 },
    },
  },
  {
    schemaVersion: 1,
    id: 'social-mob-discovers-harmony',
    name: 'MOB DISCOVERS HARMONY',
    category: 'social',
    description: 'A rhythmically excited crowd accidentally becomes a coordinated harmonic organism.',
    defaultIntensity: 80,
    tags: ['social', 'crowd', 'harmony', 'discovery'],
    owns: ['socialBehavior', 'harmonicTrajectory', 'vocalBehavior'],
    biases: ['chant to chord', 'group discovery', 'unison fracture'],
    protects: ['harmonic coordination emerges from social participation'],
    forbids: ['perfect choir voicing from the start'],
    operators: [
      'Begin with unison or chant-like group behavior and let repeated participation expose pitch differences.',
      'Convert those pitch differences into increasingly stable harmony without losing the crowd rhythm.',
    ],
    outputs: {
      musicMechanismRefs: [
        { id: 'group-unison-burst', strength: 84 },
        { id: 'communal-infection', strength: 78 },
      ],
      musicControlDeltas: { socialInfection: 28, castSize: 24, coupling: 10 },
    },
  },

  // ---------------------------------------------------------------------------
  // WORLD PACKAGES — coherent semantic handholds for otherwise insane music
  // ---------------------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'world-midnight-call-in-radio',
    name: 'MIDNIGHT CALL-IN RADIO',
    category: 'worldPackage',
    description: 'A dry late-night host keeps taking calls about one increasingly impossible recurring event.',
    defaultIntensity: 100,
    tags: ['radio', 'call-in', 'late-night', 'coherence-spine'],
    owns: ['semanticWorld', 'cast', 'medium', 'eventLogic'],
    biases: ['deadpan host', 'call queue', 'station IDs', 'phone interruptions'],
    protects: ['the event remains recognizably a live call-in radio program'],
    forbids: ['abandoning the broadcast frame', 'turning every line into abstract psychedelic narration'],
    operators: [
      'Return repeatedly to host procedure: identify caller, ask a question, respond, reset the topic, move to the next line.',
      'Let callers introduce strangeness while the host keeps trying to conduct ordinary radio.',
    ],
    collisionMode: 'protect',
    worldFrame: {
      setting: 'a tiny radio studio after midnight',
      medium: 'live call-in radio broadcast',
      primaryCharacter: 'a dry, slightly tired night host',
      supportingCast: ['callers', 'station engineer', 'prerecorded station voice'],
      recurringConcern: 'different callers keep reporting versions of the same unexplained event',
      eventCues: ['phone rings', 'caller connects', 'host interrupts', 'station ID', 'commercial break', 'line drops'],
      invariant: 'the host keeps trying to conduct an ordinary live radio show',
    },
    outputs: {
      realityEngineIds: ['format-call-in-radio', 'tone-deadpan'],
      realityChaos: 2,
    },
  },
  {
    schemaVersion: 1,
    id: 'world-public-access-hell',
    name: 'PUBLIC-ACCESS TV HELL',
    category: 'worldPackage',
    description: 'An earnest local cable host presents Hell as if it were a normal underfunded community program.',
    defaultIntensity: 100,
    tags: ['tv', 'public-access', 'hell', 'host'],
    owns: ['semanticWorld', 'cast', 'medium', 'eventLogic'],
    biases: ['cheap studio', 'awkward transitions', 'sponsor mentions', 'earnest professionalism'],
    protects: ['the cheap local-TV program remains the stable frame'],
    forbids: ['generic horror narration', 'cinematic demon monologue'],
    operators: [
      'Treat impossible infernal material as routine local programming logistics.',
      'Use airtime, callers, graphics, sponsor reads, and awkward transitions as recurring structure.',
    ],
    collisionMode: 'protect',
    worldFrame: {
      setting: 'an underfunded local cable studio located in Hell',
      medium: 'live public-access television',
      primaryCharacter: 'an earnest public-access host',
      supportingCast: ['caller', 'camera operator', 'local guest', 'station announcer'],
      recurringConcern: 'the host must finish tonight\'s community program despite infernal conditions',
      eventCues: ['camera goes live', 'caller arrives', 'homemade graphic', 'sponsor mention', 'dead air', 'airtime warning'],
      invariant: 'this remains a sincere low-budget public-access show',
    },
    outputs: {
      realityEngineIds: ['format-public-access-show', 'role-public-access-host', 'world-hell', 'tone-local-tv'],
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'world-local-news-end-reality',
    name: 'LOCAL WEATHER AT THE END OF REALITY',
    category: 'worldPackage',
    description: 'A meteorologist reports impossible conditions with ordinary forecast discipline.',
    defaultIntensity: 100,
    tags: ['weather', 'news', 'professional', 'apocalypse-but-normal'],
    owns: ['semanticWorld', 'cast', 'medium', 'eventLogic'],
    biases: ['maps', 'fronts', 'warnings', 'five-day outlook', 'professional calm'],
    protects: ['everything remains reportable as weather'],
    forbids: ['abandoning measurements for vague cosmic poetry'],
    operators: [
      'Translate each strange development into forecast variables: movement, intensity, timing, probability, region.',
      'Return to map updates and practical viewer guidance after every impossible reveal.',
    ],
    collisionMode: 'protect',
    worldFrame: {
      setting: 'a local television weather desk during impossible atmospheric conditions',
      medium: 'live local weather forecast',
      primaryCharacter: 'a relentlessly professional meteorologist',
      supportingCast: ['studio anchor', 'field reporter', 'off-camera producer'],
      recurringConcern: 'the forecast keeps getting stranger but must remain useful to viewers',
      eventCues: ['radar update', 'warning issued', 'camera toss', 'map changes', 'five-day outlook'],
      invariant: 'the impossible event is still being covered as a local weather forecast',
    },
    outputs: {
      realityEngineIds: ['format-weather-forecast', 'role-meteorologist', 'tone-hyper-professional'],
      realityChaos: 2,
    },
  },
  {
    schemaVersion: 1,
    id: 'world-demonic-customer-service',
    name: 'DEMONIC CUSTOMER SERVICE',
    category: 'worldPackage',
    description: 'Hell is a bureaucracy and one support rep is obligated to close the ticket.',
    defaultIntensity: 100,
    tags: ['hell', 'customer-service', 'bureaucracy', 'phone'],
    owns: ['semanticWorld', 'cast', 'medium', 'eventLogic'],
    biases: ['ticket numbers', 'hold procedure', 'escalation path', 'scripted empathy'],
    protects: ['the case remains an ordinary support ticket to the representative'],
    forbids: ['demon abandons procedure to become a generic villain'],
    operators: [
      'Route every supernatural problem through ordinary troubleshooting and escalation procedure.',
      'Preserve case numbers, hold states, scripted confirmations, and supervisor transfers as recurring anchors.',
    ],
    collisionMode: 'protect',
    worldFrame: {
      setting: 'a customer-support call center in Hell',
      medium: 'live support telephone call',
      primaryCharacter: 'a demon customer-support representative following policy',
      supportingCast: ['caller', 'supervisor', 'hold-message voice', 'quality-assurance monitor'],
      recurringConcern: 'the representative must resolve one impossible ticket without violating procedure',
      eventCues: ['ticket opened', 'identity verified', 'hold music', 'supervisor transfer', 'case note', 'ticket closure attempt'],
      invariant: 'the infernal crisis is still being handled as a customer-support case',
    },
    outputs: {
      realityEngineIds: ['format-customer-support-call', 'role-customer-support-rep', 'world-hell', 'tone-corporate-training'],
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'world-game-show-impossible-rules',
    name: 'GAME SHOW OF INCOMPREHENSIBLE RULES',
    category: 'worldPackage',
    description: 'A cheerful host maintains rounds, scoring, buzzers, and prizes while the rules mutate.',
    defaultIntensity: 100,
    tags: ['game-show', 'host', 'rules', 'audience'],
    owns: ['semanticWorld', 'cast', 'medium', 'eventLogic'],
    biases: ['rounds', 'buzzer', 'score updates', 'audience reaction', 'prize reveal'],
    protects: ['the audience can always tell that this is a game show'],
    forbids: ['rules dissolve into random surreal narration'],
    operators: [
      'Every rule mutation must alter scoring, eligibility, turn order, or prize conditions.',
      'Use buzzer, score, and round announcements as semantic reset points.',
    ],
    collisionMode: 'protect',
    worldFrame: {
      setting: 'an aggressively cheerful television game-show set',
      medium: 'live televised contest',
      primaryCharacter: 'a host who treats every new rule as perfectly normal',
      supportingCast: ['contestants', 'announcer', 'studio audience', 'scorekeeper'],
      recurringConcern: 'the show must determine a winner even though the rules keep changing',
      eventCues: ['buzzer', 'score update', 'new round', 'wrong answer', 'prize reveal', 'audience gasp'],
      invariant: 'this remains a scored game show with a host, contestants, rounds, and consequences',
    },
    outputs: {
      realityEngineIds: ['format-90s-game-show', 'role-game-show-host', 'tone-local-tv'],
      realityChaos: 3,
    },
  },
  {
    schemaVersion: 1,
    id: 'world-mission-control-bad-idea',
    name: 'MISSION CONTROL FOR A BAD IDEA',
    category: 'worldPackage',
    description: 'A flight controller keeps issuing telemetry and go/no-go decisions for something that should never have launched.',
    defaultIntensity: 100,
    tags: ['mission-control', 'telemetry', 'procedure', 'bad-idea'],
    owns: ['semanticWorld', 'cast', 'medium', 'eventLogic'],
    biases: ['status calls', 'telemetry', 'checklists', 'go-no-go'],
    protects: ['mission-control procedure remains the interpretive frame'],
    forbids: ['generic space-opera exposition'],
    operators: [
      'Convert every new musical or narrative disruption into a status change, telemetry anomaly, or procedure call.',
      'Keep one mission objective alive while individual systems fail or report contradictory data.',
    ],
    collisionMode: 'protect',
    worldFrame: {
      setting: 'mission control during an increasingly indefensible experiment',
      medium: 'live control-room communications and black-box telemetry',
      primaryCharacter: 'a flight controller trying to keep the mission procedural',
      supportingCast: ['vehicle crew', 'systems officers', 'automated warning voice', 'public-affairs loop'],
      recurringConcern: 'the mission must continue long enough to understand what has gone wrong',
      eventCues: ['status poll', 'telemetry spike', 'warning alarm', 'go-no-go call', 'loss of signal', 'reacquisition'],
      invariant: 'the impossible event is still being managed as a live mission-control operation',
    },
    outputs: {
      realityEngineIds: ['format-black-box-recorder', 'role-flight-controller', 'tone-clinical'],
      realityChaos: 3,
    },
  },

  // ---------------------------------------------------------------------------
  // INSTRUMENT COLLISION PACKS — eight sources, eight jobs
  // ---------------------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'instruments-wrong-ensemble-01',
    name: 'WRONG ENSEMBLE PIT #1',
    category: 'instrumentPack',
    description: 'Eight sources that look like they were booked for eight different gigs and then forced to cooperate.',
    defaultIntensity: 86,
    tags: ['instruments', 'collision', 'eight-pack'],
    owns: ['instrumentation', 'timbre', 'arrangement'],
    biases: ['distinct roles', 'register separation', 'physical articulation'],
    protects: ['all eight sources remain individually identifiable'],
    forbids: ['all sources doubled into the same rhythm', 'generic orchestral blend'],
    operators: [
      'Give every source one primary job and preserve its characteristic attack, sustain, noise, or resonance.',
      'When two sources overlap, their jobs must remain different.',
    ],
    outputs: {
      compositionEngineIds: [
        'sound-kora',
        'sound-sewing-machine',
        'sound-daxophone',
        'sound-microwave-beeps',
        'sound-whisper-cloud',
        'sound-metal-tank-resonance',
        'sound-frog-chorus',
        'sound-glass-harmonica',
      ],
      musicMechanismRefs: [{ id: 'dry-separation', strength: 92 }],
      musicControlDeltas: { stemminess: 34 },
    },
    instrumentRoles: instrumentRoles([
      ['sound-kora', 'pulse lattice', 'Own the flowing interlocked pulse and never become generic harp wash.'],
      ['sound-sewing-machine', 'high-frequency motor subdivision', 'Own relentless mechanical subdivision and controllable acceleration.'],
      ['sound-daxophone', 'melodic mutation voice', 'Own bent vocal-like lead answers and structural yelps.'],
      ['sound-microwave-beeps', 'event cue', 'Own rigid coded punctuation and section-ending signals.'],
      ['sound-whisper-cloud', 'noise floor / consonant texture', 'Own moving unpitched articulation around the vocal field.'],
      ['sound-metal-tank-resonance', 'space / drone', 'Own long metallic resonance and low spatial glue.'],
      ['sound-frog-chorus', 'social response', 'Own irregular call-and-response populations.'],
      ['sound-glass-harmonica', 'harmonic light', 'Own sustained bright upper harmony and fragile arrivals.'],
    ]),
  },
  {
    schemaVersion: 1,
    id: 'instruments-wrong-ensemble-02',
    name: 'WRONG ENSEMBLE PIT #2',
    category: 'instrumentPack',
    description: 'Accordion, glass sculpture, shopping cart, mouth clicks, mbira, blender, goose flock, and cave drips. Obviously.',
    defaultIntensity: 88,
    tags: ['instruments', 'collision', 'eight-pack', 'absurd'],
    owns: ['instrumentation', 'timbre', 'arrangement'],
    biases: ['role contrast', 'hard cues', 'physical sound sources'],
    protects: ['the weird sources do musical jobs instead of appearing as novelty sound effects'],
    forbids: ['comedy-SFX pileup', 'all eight sources playing continuously'],
    operators: [
      'Rotate prominence so no more than three or four sources dominate at once.',
      'Use the other sources as triggers, transitions, responses, or anchors rather than constant layers.',
    ],
    outputs: {
      compositionEngineIds: [
        'sound-accordion',
        'sound-cristal-baschet',
        'sound-shopping-cart',
        'sound-tongue-clicks',
        'sound-mbira',
        'sound-blender',
        'sound-goose-flock',
        'sound-cave-drips',
      ],
      musicMechanismRefs: [
        { id: 'exposure-windows', strength: 86 },
        { id: 'role-migration', strength: 76 },
      ],
      musicControlDeltas: { stemminess: 34, interruption: 10 },
    },
    instrumentRoles: instrumentRoles([
      ['sound-accordion', 'harmonic pump', 'Own chordal breathing and rhythmic harmonic punctuation.'],
      ['sound-cristal-baschet', 'luminous lead', 'Own glassy sustained melody and impossible bright arrivals.'],
      ['sound-shopping-cart', 'rolling polymeter', 'Own wheel pulse and bad-caster rhythmic friction.'],
      ['sound-tongue-clicks', 'micro-percussion', 'Own dry close rhythmic subdivision.'],
      ['sound-mbira', 'anchor lattice', 'Own the repeating interlock that survives other mutations.'],
      ['sound-blender', 'structural damage cue', 'Own brutal motor gates and pitch-noise load changes at transitions.'],
      ['sound-goose-flock', 'crowd brass', 'Own nasal antiphonal bursts and unruly social interruption.'],
      ['sound-cave-drips', 'sparse time marker', 'Own isolated high-contrast temporal punctuation.'],
    ]),
  },
  {
    schemaVersion: 1,
    id: 'instruments-wrong-ensemble-03',
    name: 'WRONG ENSEMBLE PIT #3',
    category: 'instrumentPack',
    description: 'Prepared piano, fax negotiation, udu, metal-roof rain, bass clarinet, circuit-bent toy, hand claps, and tunnel resonance.',
    defaultIntensity: 86,
    tags: ['instruments', 'collision', 'eight-pack', 'mechanical'],
    owns: ['instrumentation', 'timbre', 'arrangement'],
    biases: ['dry attacks', 'coded tones', 'body percussion', 'resonant space'],
    protects: ['each source keeps a separate rhythmic or spectral territory'],
    forbids: ['same-register masking', 'huge shared reverb on everything'],
    operators: [
      'Assign low, mid, high, transient, sustained, coded, human, and spatial jobs separately.',
      'Use tunnel resonance on selected events rather than smearing the entire ensemble.',
    ],
    outputs: {
      compositionEngineIds: [
        'sound-prepared-piano',
        'sound-fax-handshake',
        'sound-udu',
        'sound-rain-metal-roof',
        'sound-bass-clarinet',
        'sound-circuit-bent-toy',
        'sound-hand-claps',
        'sound-long-tunnel',
      ],
      musicMechanismRefs: [{ id: 'dry-separation', strength: 94 }],
      musicControlDeltas: { stemminess: 38, coupling: 8 },
    },
    instrumentRoles: instrumentRoles([
      ['sound-prepared-piano', 'pitched percussion grid', 'Own clipped pitch attacks and irregular metallic/wooden articulation.'],
      ['sound-fax-handshake', 'coded transition', 'Own negotiation chirps that announce structural state changes.'],
      ['sound-udu', 'bass pulse', 'Own deep air-hole bass and dry ceramic secondary attacks.'],
      ['sound-rain-metal-roof', 'granular subdivision', 'Own stochastic high-frequency activity whose density changes by section.'],
      ['sound-bass-clarinet', 'low melodic counterline', 'Own mobile low-register phrasing rather than drone.'],
      ['sound-circuit-bent-toy', 'mutation intruder', 'Appear during rule changes with unstable toy-electronic gestures.'],
      ['sound-hand-claps', 'human alignment point', 'Own shared bodily accents that keep the weird clocks graspable.'],
      ['sound-long-tunnel', 'secondary meter / space', 'Own delayed echoes that create another measurable temporal layer.'],
    ]),
  },
  {
    schemaVersion: 1,
    id: 'instruments-wrong-ensemble-04',
    name: 'WRONG ENSEMBLE PIT #4',
    category: 'instrumentPack',
    description: 'Vibraphone, shekere, VHS transport, bee swarm, silverware, clean guitar, heartbeat, and dolphin clicks.',
    defaultIntensity: 84,
    tags: ['instruments', 'collision', 'eight-pack', 'bright'],
    owns: ['instrumentation', 'timbre', 'arrangement'],
    biases: ['bright attacks', 'multiple pulse scales', 'mechanical transitions'],
    protects: ['one human-readable groove survives the swarm'],
    forbids: ['nature ambience bed', 'retro texture pasted on top'],
    operators: [
      'Make the heartbeat or shekere provide the most stable bodily reference while other sources occupy faster or stranger clocks.',
      'Use VHS transport states as arrangement commands rather than background nostalgia.',
    ],
    outputs: {
      compositionEngineIds: [
        'sound-vibraphone',
        'sound-shekere',
        'sound-vhs-mechanism',
        'sound-bee-swarm',
        'sound-silverware',
        'sound-electric-guitar-clean',
        'sound-heartbeat',
        'sound-dolphin-clicks',
      ],
      musicMechanismRefs: [
        { id: 'meter-collision', strength: 72 },
        { id: 'anchor-survival', strength: 74 },
      ],
      musicControlDeltas: { coupling: 20, kineticDensity: 18, stemminess: 24 },
    },
    instrumentRoles: instrumentRoles([
      ['sound-vibraphone', 'harmonic punctuation', 'Own clear struck pitch arrivals and short harmonic statements.'],
      ['sound-shekere', 'continuous subdivision', 'Own granular hand-played motion and phrase punctuation.'],
      ['sound-vhs-mechanism', 'form command', 'Load, play, rewind, stop, and eject states trigger arrangement changes.'],
      ['sound-bee-swarm', 'moving drone density', 'Own a pitched-ish density field whose thickness changes with intensity.'],
      ['sound-silverware', 'micro-metal ornaments', 'Own tiny high-frequency scrapes, clacks, and drops.'],
      ['sound-electric-guitar-clean', 'syncopated midrange anchor', 'Own clipped melodic/pulse figures with exposed articulation.'],
      ['sound-heartbeat', 'slow bodily clock', 'Own the stubborn low paired pulse independent of musical tempo.'],
      ['sound-dolphin-clicks', 'burst accelerator', 'Own rapid click-train transitions and short granular runs.'],
    ]),
  },
];

export const STARTER_SEEDS_BY_CATEGORY = STARTER_SEEDS.reduce<Record<string, StarterSeedDefinition[]>>(
  (acc, seed) => {
    if (!acc[seed.category]) acc[seed.category] = [];
    acc[seed.category].push(seed);
    return acc;
  },
  {},
);

export function getStarterSeed(id: string): StarterSeedDefinition | undefined {
  return STARTER_SEEDS.find((seed) => seed.id === id);
}
