import { MouthTrait } from './types';

const LEDGER = 'docs/LANGUAGE_PHONOLOGY_SOURCE_LEDGER.md';

function trait(
  id: string,
  name: string,
  category: MouthTrait['category'],
  axes: MouthTrait['axes'],
  shortExplanation: string,
  operation: string,
  tags: string[],
  musicalAffordances: string[],
  donorProfileIds: string[],
  defaultPressure: MouthTrait['defaultPressure'] = 'medium',
  confidence: MouthTrait['confidence'] = 'high',
  cautions: string[] = [],
  extraSourceNotes: string[] = [],
): MouthTrait {
  return {
    id,
    name,
    category,
    axes,
    shortExplanation,
    operation,
    tags,
    musicalAffordances,
    donorProfileIds,
    defaultPressure,
    confidence,
    sourceNotes: [
      LEDGER,
      'docs/MOUTH_LAB_SOURCE_LEDGER.md',
      ...donorProfileIds.map((profileId) => 'src/data/languageProfiles.ts#' + profileId),
      ...extraSourceNotes,
    ],
    cautions,
  };
}

export const MOUTH_TRAITS: MouthTrait[] = [
  trait(
    'mouth-trait-alveolar-trill',
    'ALVEOLAR TRILL',
    'segment',
    ['consonants'],
    'Rhotic positions can become taps or sustained tongue-tip trills.',
    'When assigned, realize eligible rhotics as audible alveolar taps/trills. Pressure controls whether this is occasional, frequent, or pathological; obsessive pressure means every eligible rhotic should announce itself.',
    ['rhotic', 'trill', 'micro-mutation', 'percussive'],
    ['rapid repeated attacks', 'comic overcommitment without changing semantics', 'rhythmic consonant rolls'],
    ['lang-spanish', 'lang-italian'],
    'high',
  ),
  trait(
    'mouth-trait-uvular-rhotic',
    'UVULAR RHOTIC',
    'segment',
    ['consonants', 'larynx'],
    'Moves rhotic color away from an English approximant toward a back-of-mouth articulation.',
    'Route eligible rhotics toward a uvular/fricative or uvular-trill color while leaving unrelated consonants alone.',
    ['rhotic', 'uvular', 'back-mouth'],
    ['rasping sustained attacks', 'dark consonant color'],
    ['lang-french', 'lang-german'],
  ),
  trait(
    'mouth-trait-nasal-vowels',
    'NASAL VOWEL CONTRAST',
    'segment',
    ['vowels', 'phonation'],
    'Nasal resonance becomes a structured vowel property rather than an incidental effect.',
    'Assign nasal resonance to selected vowel classes or contexts and preserve the contrast consistently enough to be heard as a rule.',
    ['nasal', 'vowel', 'resonance'],
    ['drone-like resonance', 'timbral vowel alternation'],
    ['lang-french', 'lang-portuguese', 'lang-guarani', 'lang-navajo', 'lang-juhoan', 'lang-taa'],
  ),
  trait(
    'mouth-trait-front-rounded-vowels',
    'FRONT-ROUNDED VOWEL FIELD',
    'segment',
    ['vowels'],
    'Adds a vowel-color dimension uncommon in mainstream English.',
    'Bias selected vowel targets toward front-rounded territory while preserving lexical identity as much as intelligibility allows.',
    ['vowel', 'front-rounded', 'color'],
    ['bright/covered vowel alternation', 'melodic timbre shifts'],
    ['lang-french', 'lang-german', 'lang-swedish', 'lang-danish', 'lang-hungarian'],
  ),
  trait(
    'mouth-trait-stod',
    'GLOTTAL INTERRUPTION / STØD PRESSURE',
    'phonation',
    ['larynx', 'phonation', 'prosody'],
    'Introduces controlled glottal constriction or interruption as a recurring prosodic event.',
    'Place brief glottal/creaky interruptions at selected stressed or structurally prominent syllables instead of adding random vocal fry everywhere.',
    ['glottal', 'creaky', 'larynx', 'micro-mutation'],
    ['hard vocal edits', 'phrase punctuation', 'tension spikes'],
    ['lang-danish'],
    'high',
  ),
  trait(
    'mouth-trait-ejective-attack',
    'EJECTIVE ATTACK',
    'segment',
    ['consonants', 'airflow', 'larynx'],
    'Selected stops/affricates gain a compressed glottalic release.',
    'Use ejective-like attacks only on eligible consonant classes; treat them as speech contrasts or controlled mutation targets, not generic sound effects.',
    ['ejective', 'glottalic', 'attack', 'percussive'],
    ['snare-like transient', 'accent marker', 'rhythmic punctuation'],
    ['lang-georgian', 'lang-navajo', 'lang-tlingit', 'lang-yucatec-maya', 'lang-hadza'],
    'high',
  ),
  trait(
    'mouth-trait-extreme-cluster',
    'EXTREME CONSONANT CLUSTERING',
    'syllable',
    ['phonotactics', 'syllableStructure', 'consonants'],
    'Permits unusually dense consonant sequences instead of repairing them with English-like vowels.',
    'Increase legal consonant adjacency and reduce automatic vowel insertion; keep clusters deliberate and repeatable rather than random consonant soup.',
    ['cluster', 'consonant-heavy', 'compression'],
    ['machine-gun articulation', 'dense rhythmic cells', 'vowel scarcity'],
    ['lang-georgian', 'lang-nuxalk', 'lang-tashlhiyt'],
    'high',
  ),
  trait(
    'mouth-trait-consonantal-nucleus',
    'CONSONANTAL NUCLEUS',
    'syllable',
    ['syllableStructure', 'phonotactics'],
    'Allows selected consonants to carry syllabic weight where English expects a vowel.',
    'Permit selected consonants to function as syllable nuclei or perceptual centers, creating vowelless or nearly vowelless rhythmic units.',
    ['syllabic-consonant', 'vowel-sparse', 'consonant-heavy'],
    ['vowelless pulse', 'noise-pitched syllables', 'dry rhythmic streams'],
    ['lang-tashlhiyt'],
    'high',
    'medium',
    ['Use as a mechanism-level abstraction; syllabification analyses are language-specific and should not be universalized.'],
  ),
  trait(
    'mouth-trait-open-syllable-pressure',
    'OPEN-SYLLABLE PRESSURE',
    'syllable',
    ['phonotactics', 'syllableStructure', 'vowels'],
    'Pushes words toward vowel-ending syllables and away from dense codas/clusters.',
    'When a source form creates disfavored clusters or codas, prefer vowel insertion, resyllabification, or simplification so the output repeatedly returns to open syllables.',
    ['open-syllable', 'repair', 'vowel-insertion'],
    ['regular pulse cells', 'vowel relief after clusters', 'clear melodic nuclei'],
    ['lang-hawaiian', 'lang-maori', 'lang-samoan', 'lang-yoruba'],
    'high',
  ),
  trait(
    'mouth-trait-click-bantu',
    'BANTU CLICK INTEGRATION',
    'segment',
    ['consonants', 'airflow'],
    'Click consonants occupy ordinary lexical consonant positions inside a syllabic/tonal flow.',
    'Use click classes as systematic consonantal events in selected positions; never sprinkle them randomly as percussion decoration.',
    ['click', 'bantu', 'airflow', 'percussive'],
    ['click hocket', 'consonant percussion', 'trigger accents'],
    ['lang-xhosa', 'lang-zulu'],
    'high',
  ),
  trait(
    'mouth-trait-click-high-dimensional',
    'HIGH-DIMENSION CLICK SYSTEM',
    'segment',
    ['consonants', 'airflow', 'larynx', 'phonation'],
    'Expands clicks across place plus laryngeal/nasal/phonation dimensions.',
    'Assign distinct click classes separate roles instead of treating every click as the same sound; keep the inventory bounded enough that roles remain audible.',
    ['click', 'high-dimensional', 'phonation', 'airflow'],
    ['multiple click-percussion voices', 'timbral consonant orchestration'],
    ['lang-taa', 'lang-juhoan', 'lang-khoekhoe'],
    'high',
  ),
  trait(
    'mouth-trait-lexical-tone',
    'LEXICAL TONE PRESSURE',
    'prosody',
    ['tone', 'prosody'],
    'Pitch contour is treated as structurally meaningful rather than free melodic decoration.',
    'Assign recurring pitch categories or contours to syllables and make melody negotiate with them instead of flattening them into ordinary English intonation.',
    ['tone', 'pitch', 'melody-control'],
    ['melody generated from syllables', 'pitch-rule hocket', 'tonal anchors'],
    ['lang-yoruba', 'lang-cantonese', 'lang-mandarin', 'lang-vietnamese', 'lang-xhosa', 'lang-navajo', 'lang-yucatec-maya', 'lang-taa'],
    'medium',
  ),
  trait(
    'mouth-trait-pitch-accent',
    'PITCH-ACCENT PRESSURE',
    'prosody',
    ['tone', 'prosody'],
    'Lexical pitch grouping constrains where melodic prominence may move.',
    'Preserve a small number of recurring pitch-accent relationships while allowing the surrounding melody to mutate.',
    ['pitch-accent', 'prosody', 'melody-control'],
    ['melodic anchor points', 'contour contrast'],
    ['lang-japanese', 'lang-swedish', 'lang-norwegian'],
  ),
  trait(
    'mouth-trait-mora-timing',
    'MORA-LIKE TIMING',
    'timing',
    ['timing', 'syllableStructure'],
    'Short timing units become compositionally explicit; length and gemination consume real rhythmic space.',
    'Segment phrases into mora-like timing units so long vowels, geminates, and coda-like timing slots change duration rather than remaining spelling details.',
    ['mora', 'timing', 'length', 'gemination'],
    ['clocked vocal subdivision', 'length-coded rhythm'],
    ['lang-japanese', 'lang-hawaiian'],
    'high',
  ),
  trait(
    'mouth-trait-three-way-quantity',
    'THREE-WAY QUANTITY',
    'timing',
    ['timing', 'vowels', 'consonants', 'prosody'],
    'Three timing degrees create a rhythmic dimension beyond simple short/long.',
    'Map three quantity levels onto clearly different durations or weights and preserve them through repeated phrases.',
    ['quantity', 'timing', 'three-way'],
    ['three-level note length', 'elastic rhythmic identity'],
    ['lang-estonian'],
    'high',
  ),
  trait(
    'mouth-trait-vowel-length',
    'CONTRASTIVE VOWEL LENGTH',
    'timing',
    ['vowels', 'timing'],
    'Vowel duration carries structural information.',
    'Make short and long vowel targets audibly different in duration; do not represent length only orthographically.',
    ['vowel-length', 'duration'],
    ['sustain rules', 'short/long rhythmic pairs'],
    ['lang-japanese', 'lang-hawaiian', 'lang-navajo', 'lang-yucatec-maya', 'lang-estonian'],
  ),
  trait(
    'mouth-trait-gemination',
    'GEMINATE CLOSURE',
    'timing',
    ['consonants', 'timing'],
    'Long consonants occupy their own timing space.',
    'Treat selected doubled/long consonants as extended closures or held constrictions that visibly alter rhythmic subdivision.',
    ['gemination', 'consonant-length', 'timing'],
    ['silent/closed rhythmic space', 'delayed release'],
    ['lang-japanese', 'lang-italian', 'lang-arabic-msa', 'lang-finnish'],
  ),
  trait(
    'mouth-trait-nasal-harmony',
    'NASAL HARMONY',
    'segment',
    ['vowels', 'phonation', 'phonotactics'],
    'Nasality spreads across a larger domain instead of staying attached to one segment.',
    'When a nasal trigger activates, propagate nasal resonance through the configured word/phrase domain until a boundary or blocker resets it.',
    ['nasal', 'harmony', 'contagion'],
    ['resonance infection', 'phrase-level timbral sweep'],
    ['lang-guarani'],
    'high',
  ),
  trait(
    'mouth-trait-vowel-harmony',
    'VOWEL HARMONY',
    'segment',
    ['vowels', 'phonotactics'],
    'Vowel qualities in one part of a word constrain later vowel choices.',
    'Choose a harmony dimension and force later eligible vowels to agree with the active class until a boundary resets the system.',
    ['vowel-harmony', 'agreement', 'contagion'],
    ['vowel-color propagation', 'morphological-sounding repetition'],
    ['lang-turkish', 'lang-hungarian', 'lang-finnish'],
    'high',
  ),
  trait(
    'mouth-trait-consonant-vowel-coupling',
    'CONSONANTS RECOLOR VOWELS',
    'segment',
    ['consonants', 'vowels', 'phonotactics'],
    'Consonant secondary articulation strongly conditions neighboring vowel realization.',
    'Let consonant class determine the color of adjacent vowels, so changing consonants automatically changes the vowel surface.',
    ['coupling', 'secondary-articulation', 'vowel-color'],
    ['cause-effect timbre chains', 'vowel mutation from consonant changes'],
    ['lang-marshallese'],
    'high',
  ),
  trait(
    'mouth-trait-lateral-fricative',
    'LATERAL FRICATIVE',
    'segment',
    ['consonants', 'airflow'],
    'Introduces a sustained lateral-noise consonant unlike ordinary English /l/.',
    'Use lateral frication as a recurring consonant color or mutation target while keeping it distinct from ordinary /l/ and /s/.',
    ['lateral', 'fricative', 'noise'],
    ['noise sustain', 'hissing lateral accents'],
    ['lang-welsh', 'lang-navajo'],
  ),
  trait(
    'mouth-trait-pharyngeal-emphatic',
    'PHARYNGEAL / EMPHATIC COLOR',
    'segment',
    ['consonants', 'vowels', 'larynx'],
    'Back-of-mouth consonant constriction can darken neighboring vowel color.',
    'Use selected pharyngeal/uvular/emphatic articulations as a controlled consonant class and allow predictable neighboring-vowel darkening.',
    ['pharyngeal', 'emphatic', 'uvular', 'back-mouth'],
    ['dark vocal color', 'consonant-triggered timbre shift'],
    ['lang-arabic-msa', 'lang-tashlhiyt'],
    'medium',
  ),
  trait(
    'mouth-trait-glottal-stop',
    'GLOTTAL STOP PUNCTUATION',
    'segment',
    ['consonants', 'larynx', 'timing'],
    'Glottal closure becomes a discrete segmentation tool.',
    'Insert or preserve glottal closure only at configured structural positions so it behaves like precise vocal punctuation.',
    ['glottal', 'closure', 'punctuation'],
    ['hard phrase segmentation', 'micro-rest articulation'],
    ['lang-hawaiian', 'lang-navajo', 'lang-yucatec-maya', 'lang-guarani'],
  ),
  trait(
    'mouth-trait-glottalized-vowels',
    'GLOTTALIZED / PHONATED VOWELS',
    'phonation',
    ['vowels', 'phonation', 'larynx'],
    'Vowel voice quality becomes an explicit contrast.',
    'Assign glottalized/creaky or otherwise marked phonation to selected vowel classes or timing positions and preserve the contrast as a rule.',
    ['phonation', 'glottalized-vowel', 'creaky'],
    ['vowel distortion layer', 'laryngeal melody'],
    ['lang-yucatec-maya', 'lang-taa', 'lang-juhoan'],
    'medium',
  ),
  trait(
    'mouth-trait-huge-consonant-palette',
    'HUGE CONSONANT PALETTE',
    'segment',
    ['consonants', 'airflow', 'larynx'],
    'The consonant system carries much more timbral information than English normally does.',
    'Favor many distinct consonant attack/color classes while keeping the vowel system comparatively stable so the consonants become the timbral orchestra.',
    ['large-inventory', 'consonant-heavy', 'timbral'],
    ['consonant orchestration', 'articulatory cast'],
    ['lang-ubykh', 'lang-taa', 'lang-juhoan'],
    'high',
  ),
  trait(
    'mouth-trait-tiny-inventory',
    'TINY INVENTORY PRESSURE',
    'segment',
    ['consonants', 'vowels', 'phonotactics'],
    'Destroys phonemic variety and forces many forms through a deliberately small mouth.',
    'Restrict available segment classes sharply and repair unsupported sounds into the remaining inventory rather than expanding the inventory to fit the source.',
    ['small-inventory', 'compression', 'lossy'],
    ['minimal-mouth challenge', 'phonetic aliasing'],
    ['lang-rotokas', 'lang-hawaiian'],
    'high',
  ),
  trait(
    'mouth-trait-vowel-starvation',
    'VOWEL STARVATION',
    'syllable',
    ['vowels', 'phonotactics', 'syllableStructure'],
    'A tiny vowel system must support a much richer consonant architecture.',
    'Keep vowel categories sparse while allowing consonant distinctions to carry most surface variety; do not compensate by inventing extra vowel qualities.',
    ['small-vowel', 'consonant-heavy', 'asymmetry'],
    ['vowel anchors inside consonant swarms', 'dry articulatory texture'],
    ['lang-ubykh', 'lang-tashlhiyt'],
    'high',
  ),
  trait(
    'mouth-trait-tone-plus-phonation',
    'TONE × PHONATION COUPLING',
    'phonation',
    ['tone', 'phonation', 'vowels'],
    'Pitch and voice quality cooperate instead of acting as independent effects.',
    'Couple selected tone classes with recurring phonation states so pitch changes can trigger breathy/creaky/glottal color and vice versa.',
    ['tone', 'phonation', 'coupling'],
    ['pitch-to-timbre transduction', 'voice-quality contours'],
    ['lang-vietnamese', 'lang-taa', 'lang-juhoan'],
    'medium',
  ),
  trait(
    'mouth-trait-prenasalized-attack',
    'PRENASALIZED ATTACK',
    'segment',
    ['consonants', 'phonation', 'timing'],
    'A short nasal onset is structurally fused with a following consonantal attack.',
    'Treat selected stop attacks as a single nasal-plus-stop gesture rather than two unrelated syllables.',
    ['prenasalized', 'attack', 'nasal'],
    ['two-stage percussion attack', 'anticipatory consonant pulse'],
    ['lang-xhosa', 'lang-zulu', 'lang-fijian'],
  ),
  trait(
    'mouth-trait-full-vowel-preservation',
    'FULL-VOWEL PRESERVATION',
    'segment',
    ['vowels', 'timing'],
    'Resists English-style unstressed-vowel collapse.',
    'Keep unstressed vowels comparatively full and audible instead of reducing every weak syllable toward schwa.',
    ['full-vowel', 'anti-reduction', 'syllabic'],
    ['clear fast patter', 'even vowel melody'],
    ['lang-spanish', 'lang-italian', 'lang-hawaiian'],
  ),
  trait(
    'mouth-trait-phrase-prosody',
    'PHRASE-LEVEL PROMINENCE',
    'prosody',
    ['prosody', 'stress', 'timing'],
    'Prominence is organized across phrases rather than by aggressively stressing each lexical word.',
    'Shape emphasis and length toward phrase-level peaks and boundaries while reducing the dominance of English-like word stress.',
    ['phrase-prosody', 'legato', 'stress-transfer'],
    ['long contour arcs', 'phrase-final lift/drop'],
    ['lang-french'],
  ),
  trait(
    'mouth-trait-bound-verb-packing',
    'BOUND VERB PACKING',
    'morphology',
    ['morphology', 'semantics', 'timing'],
    'Information that English distributes across separate words is pressured toward a larger bound verb complex.',
    'Preserve a semantic root while subject/object-like roles, mode/aspect-like information, and tense-like information accumulate as ordered bound layers. When applied to English material, this is a structural mutation only: do not fabricate Cherokee-looking strings or claim grammatical Cherokee.',
    ['morphology', 'agglutinative', 'verb-complex', 'word-packing', 'cherokee'],
    ['phrase compression', 'layer-by-layer rhythmic growth', 'one-word escalation'],
    ['lang-cherokee'],
    'high',
    'high',
    [
      'Do not treat the generated hybrid as Cherokee grammar.',
      'Preserve the distinction between a Cherokee-derived structural pressure and authentic Cherokee forms.',
    ],
    ['https://language.cherokee.org/media/vnihnhms/learning-to-use-the-cherokee-verb.pdf'],
  ),
  trait(
    'mouth-trait-polysynthetic-suffix-chain',
    'POLYSYNTHETIC SUFFIX CHAIN',
    'morphology',
    ['morphology', 'semantics', 'timing', 'phonotactics'],
    'A lexical root accumulates many functional chunks so one vocal word can carry increasingly clause-like information.',
    'Start from a recognizable root and add ordered suffix-like functional chunks across repetitions. Let longer chains occupy more rhythmic space, and allow root-boundary contact to trigger controlled phonetic mutation. Applied to English, this produces an invented hybrid mechanism, not Inuktitut text.',
    ['morphology', 'polysynthesis', 'suffix-chain', 'word-packing', 'inuktitut'],
    ['mega-word crescendo', 'morpheme-by-morpheme rhythm', 'boundary-triggered mutation'],
    ['lang-inuktitut'],
    'high',
    'high',
    ['Do not invent pseudo-Inuktitut morphemes or claim the hybrid chain is grammatical Inuktitut.'],
    ['https://linguistics.washington.edu/news/2020/10/02/featured-language-inuktitut'],
  ),
  trait(
    'mouth-trait-agglutinative-chain',
    'AGGLUTINATIVE CHAIN',
    'morphology',
    ['morphology', 'vowels', 'timing'],
    'A stable stem grows through clearly segmented ordered suffix-like additions.',
    'Keep a recognizable stem invariant while successive functional units attach one at a time. Each addition should remain legible as another layer; when paired with vowel harmony, the added material must negotiate with the active vowel class.',
    ['morphology', 'agglutinative', 'suffix-chain', 'turkish'],
    ['incremental phrase growth', 'suffix-triggered arrangement events', 'vowel-harmony coupling'],
    ['lang-turkish'],
    'medium',
    'high',
    ['Use as a structural transfer; invented chains are not authentic Turkish.'],
    ['https://www.cambridge.org/core/books/abs/student-grammar-of-turkish/introduction/5C534399EFE43902C585A533DE92F6E6'],
  ),
  trait(
    'mouth-trait-root-pattern-interlock',
    'ROOT / PATTERN INTERLOCK',
    'morphology',
    ['morphology', 'consonants', 'vowels'],
    'A recurring segmental skeleton keeps lexical identity while interleaved vowel/template patterns change the derived form.',
    'Preserve a consonantal or segmental root skeleton across related forms while changing the interlocked vowel/template pattern. The root and pattern must negotiate simultaneously rather than behaving as a simple suffix chain.',
    ['morphology', 'root-pattern', 'nonconcatenative', 'arabic', 'interlock'],
    ['same consonant skeleton under changing vowel melodies', 'template-driven derivation', 'vowel-pattern orchestration'],
    ['lang-arabic-msa'],
    'medium',
    'high',
    [
      'Not every Arabic lexical item is generated exclusively by root-pattern morphology.',
      'Applied to English, this is an invented structural transformation, not authentic Arabic.',
    ],
    [
      'https://www.cambridge.org/core/books/abs/arabic/derivational-morphology-the-rootpattern-system/DBE7A3A92000E1F1AA40C23DD68B17EE',
      'https://www.cambridge.org/core/books/reference-grammar-of-modern-standard-arabic/207FA6CB610D541184C4B8CB10A4084A/listing',
    ],
  ),
];

export const MOUTH_TRAIT_BY_ID = new Map(MOUTH_TRAITS.map((item) => [item.id, item]));

export function getMouthTrait(id: string): MouthTrait | undefined {
  return MOUTH_TRAIT_BY_ID.get(id);
}

export function searchMouthTraits(query: string): MouthTrait[] {
  const needle = query.trim().toLowerCase();
  if (!needle) return MOUTH_TRAITS;

  return MOUTH_TRAITS.filter((item) =>
    [
      item.name,
      item.shortExplanation,
      item.operation,
      ...item.tags,
      ...item.musicalAffordances,
    ]
      .join(' ')
      .toLowerCase()
      .includes(needle),
  );
}
